### ISSUE TITLE
Building and running in Docker container produces a segmentation fault

### ISSUE THREAD

**Issue by KhaledSharif** [NerdyPepper/taizen#5]
Dockerfile contents:

```
FROM liuchong/rustup:stable

RUN apt update
RUN apt install -y libssl-dev pkg-config libncursesw5-dev git

WORKDIR /
RUN git clone https://github.com/NerdyPepper/taizen.git

WORKDIR /taizen
RUN cargo build
ENTRYPOINT cargo run
```

Output of running container:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/taizen`
Segmentation fault (core dumped)
```

**Comment by gyscos** [comment]
Taizen needs a UTF-8 locale; you may need to add this to the Dockerfile, otherwise you'll get messy borders:

```
env LANG C.UTF-8
env LC_ALL C.UTF-8
```

Also, it seems this image is lacking full color support, and only supports 8 colors (as opposed to the 16 most terminal emulators support), so some content may be unreadable with the current theme.

Still, it should work if you assign a TTY to the container:

```
docker run -it IMAGE_ID
```

**Comment by KhaledSharif** [comment]
@gyscos thanks for your comments. I tried both and it still doesn't work, however the behavior changes. Now instead of a segmentation fault, I get a infinite blank screen.

**Comment by gyscos** [comment]
This is the start screen of taizen. Press 's' to open the search box.

**Comment by oppiliappan** [comment]
Ill add a 'splash' screen soon!

Edit: a splash screen has been added!
